### ISSUE TITLE
nopt and WebStorm 11

### ISSUE THREAD

**Issue by ghaiklor** [npm/nopt#53]
Hi there!

I have an issue with running Yeoman generator in WebStorm 11. Getting the following error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'match' of undefined
    at parse (/Users/ghaiklor/Library/Caches/WebStorm11/extLibs/yeoman/generators_local/generator-sails-rest-api/node_modules/nopt/lib/nopt.js:239:12)
    at nopt (/Users/ghaiklor/Library/Caches/WebStorm11/extLibs/yeoman/generators_local/generator-sails-rest-api/node_modules/nopt/lib/nopt.js:40:3)
    at ControllerGenerator.Base.parseOptions (/Users/ghaiklor/Library/Caches/WebStorm11/extLibs/yeoman/generators_local/generator-sails-rest-api/node_modules/yeoman-generator/lib/base.js:345:10)
    at ControllerGenerator.option (/Users/ghaiklor/Library/Caches/WebStorm11/extLibs/yeoman/generators_local/generator-sails-rest-api/node_modules/yeoman-generator/lib/base.js:275:8)
    at ControllerGenerator.Base (/Users/ghaiklor/Library/Caches/WebStorm11/extLibs/yeoman/generators_local/generator-sails-rest-api/node_modules/yeoman-generator/lib/base.js:85:8)
    at new ControllerGenerator (/Users/ghaiklor/Library/Caches/WebStorm11/extLibs/yeoman/generators_local/generator-sails-rest-api/node_modules/generator-sails-rest-api/generators/controller/index.js:43:85)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:297:10)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:274:15)
    at AppGenerator.composeWith (/Users/ghaiklor/Library/Caches/WebStorm11/extLibs/yeoman/generators_local/generator-sails-rest-api/node_modules/yeoman-generator/lib/base.js:623:26)
    at /Users/ghaiklor/Library/Caches/WebStorm11/extLibs/yeoman/generators_local/generator-sails-rest-api/node_modules/generator-sails-rest-api/generators/app/steps/default.js:49:11
```

I'd made a little research and seems that issue in `parse` method - https://github.com/npm/nopt/blob/master/lib/nopt.js#L228

I'm wondering if this issues is nopt related, Yeoman or WebStorm itself.

**Comment by ghaiklor** [comment]
Summoning @SBoudrias for helping out with this issue.
