### ISSUE TITLE
3.0.5 release failing to install on my build server

### ISSUE THREAD

**Issue by scriby** [npm/nopt#54]
I'm still gathering details, but figured I'd go ahead and report it.

```
16:38:00 /usr/local/jenkins/workspace/ultra-learn-ultra-ui_develop-ui-test/node_modules/grunt-sass/node_modules/node-sass/node_modules/npmconf/node_modules/nopt/lib/nopt.js:210
16:38:00     if (t && ((type.name && t.type.name) ?
16:38:00                    ^
16:38:00 TypeError: Cannot read property 'name' of null
16:38:00     at validate (/usr/local/jenkins/workspace/ultra-learn-ultra-ui_develop-ui-test/node_modules/grunt-sass/node_modules/node-sass/node_modules/npmconf/node_modules/nopt/lib/nopt.js:210:20)
16:38:00     at validate (/usr/local/jenkins/workspace/ultra-learn-ultra-ui_develop-ui-test/node_modules/grunt-sass/node_modules/node-sass/node_modules/npmconf/node_modules/nopt/lib/nopt.js:179:11)
16:38:00     at /usr/local/jenkins/workspace/ultra-learn-ultra-ui_develop-ui-test/node_modules/grunt-sass/node_modules/node-sass/node_modules/npmconf/node_modules/nopt/lib/nopt.js:101:12
16:38:00     at Array.map (native)
16:38:00     at /usr/local/jenkins/workspace/ultra-learn-ultra-ui_develop-ui-test/node_modules/grunt-sass/node_modules/node-sass/node_modules/npmconf/node_modules/nopt/lib/nopt.js:67:15
16:38:00     at Array.forEach (native)
16:38:00     at Function.clean (/usr/local/jenkins/workspace/ultra-learn-ultra-ui_develop-ui-test/node_modules/grunt-sass/node_modules/node-sass/node_modules/npmconf/node_modules/nopt/lib/nopt.js:55:21)
16:38:00     at /usr/local/jenkins/workspace/ultra-learn-ultra-ui_develop-ui-test/node_modules/grunt-sass/node_modules/node-sass/node_modules/npmconf/npmconf.js:411:10
16:38:00     at Array.forEach (native)
16:38:00     at validate (/usr/local/jenkins/workspace/ultra-learn-ultra-ui_develop-ui-test/node_modules/grunt-sass/node_modules/node-sass/node_modules/npmconf/npmconf.js:410:11)
```

**Comment by jsg2021** [comment]
yep... installing node-sass triggers this.

**Comment by kenips** [comment]
:+1:

**Comment by blimmer** [comment]
+1

**Comment by awikkerink** [comment]
+1

**Comment by jonnystoten** [comment]
+1

**Comment by etburke** [comment]
+1

**Comment by minustime** [comment]
+1

**Comment by mattbailey** [comment]
oh lawdy :+1:

**Comment by dzonatan** [comment]
+1

**Comment by baziger** [comment]
+1

**Comment by reklawnos** [comment]
+1

**Comment by leslie-fugue** [comment]
+1

**Comment by radovsky** [comment]
+1

**Comment by austindebruyn** [comment]
+1

**Comment by ebordeau** [comment]
+1

**Comment by othiym23** [comment]
Yep, I'm working on getting a new version out right now.

**Comment by kenips** [comment]
:+1: works. thanks!

**Comment by scriby** [comment]
Thanks!

**Comment by othiym23** [comment]
The fix is landed as 8900f8e3f039d5131c600700994e51f7b312c5fe, and `nopt@3.0.6` has been published to the registry.

**Comment by mattbailey** [comment]
many many thanks

**Comment by dseeto** [comment]
Great job @othiym23!

**Comment by danoc** [comment]
Thanks for fixing so quickly, @othiym23. Saved many headaches!
